
const mlActionType={
    STORE_CROP_IMAGE_DATA:'STORE_CROP_IMAGE_DATA',
    STORE_UNCROP_IMAGE_DATA:'STORE_UNCROP_IMAGE_DATA',
    GET_CROP_IMAGE:'GET_CROP_IMAGE',
    GET_UNCROP_IMAGE:'GET_UNCROP_IMAGE',
    FETCH_FORM_DATA:'FETCH_FORM_DATA',
    CLEAR_DATA:'CLEAR_DATA',
    CONTROL_FLAG:'CONTROL_FLAG',
    STORE_FORM_DATA:'STORE_FORM_DATA',
    UPDATE_FORM_DATA:'UPDATE_FORM_DATA'
}
export default mlActionType;